source 'https://rubygems.org'

# NOTE: Avoid putting development deps in gemspec
gemspec development_group: :gem_build_tools

gem 'rspec', '~> 3.1', groups: [:test, :development]
gem 'rake', group: :gem_build_tools
