#!/usr/bin/env rake
require "bundler/gem_tasks"
require 'fileutils'
require 'pathname'

ROOT_PATH = Pathname.new(File.expand_path("../../", __FILE__))
RUBYGEM_PATH = Pathname.new(File.expand_path("../", __FILE__))

task default: :build

